FROM docker.io/bitnami/redis:latest

# Installation des outils nécessaires
USER root
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

# Configuration de sysctl vm.overcommit_memory=1
RUN echo "vm.overcommit_memory=1" >> /etc/sysctl.conf

# RUN sysctl -p

# Retour à l'utilisateur bitnami
USER 1001
