version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  belife-apis:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    restart: always
    ports:
      - '3500:3500'
    environment:
      - NODE_ENV=$NODE_ENV
      - NODE_USSD_API_KEY=$NODE_USSD_API_KEY
      - NODE_SESSION_SECRET=$NODE_SESSION_SECRET
      - PSQL_HOST=$PSQL_HOST
      - PSQL_USER=$PSQL_USER
      - PSQL_USER_PASSWORD=$PSQL_USER_PASSWORD
      - PSQL_DB_NAME=$PSQL_DB_NAME
      - PSQL_PORT=$PSQL_PORT
      - PSQL_DRIVER=$PSQL_DRIVER
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
      - REDIS_DATABASE=$REDIS_DATABASE
    container_name: belife_apis_con
    volumes:
      - ./:/workspace
      - dummy:/workspace/.venv
    networks:
      - app-tier
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:7
    container_name: belife_jobs_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    volumes:
      - redis_data:/data
    networks:
      - app-tier
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  postgres:
    image: postgres:15
    container_name: belife_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_USER_PASSWORD
      - POSTGRES_DB=$PSQL_DB_NAME
    ports:
      - "$PSQL_PORT:$PSQL_PORT"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-tier
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  dummy:
  redis_data:
    driver: local
  pg_data:
    driver: local
